### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by haoyi-duan** [YangLing0818/Trans4D#1]
Hi, nice work! What is the entire running time for a single text-to-4D?

**Comment by zengbohan0217** [comment]
Thank you very much for your interest in our work. On an A100 GPU, it takes 2-3 hours to fully complete stages 1, 2, and 3. The time required to complete stages 1 and 2, along with comp4D, is similar, around 1-2 hours. Other methods, such as 4dfy, consistent4D, and 4Diffusion, take considerable time—often even longer than ours—to optimize 4D results. Therefore, speeding up user-friendly conditions for 4D generation is an issue that urgently needs to be addressed. Wishing you success in your research.
